### ISSUE TITLE
element.all option not there for ancestor control

### ISSUE THREAD

**Issue by nipun0212** [SAP/ui5-uiveri5#76]
var e = element(by.id("page1-intHeader-BarLeft")) // can be any locator
  .element(by.control({
    controlType: "sap.m.Button"
  })); // will look for buttons in the header

The above code will return a lot of buttons and you can't loop over each button as e.each is not a function we are finding element not element.all. 

Can element.all can be added for finding children?

**Comment by maximnaidenov** [comment]
Hi,
the correct syntax is :  element.all(by.control(…)). Please check the docs at: https://www.protractortest.org/#/api
Also note that it is generally a bad practice to loop over elements, compose a precise locator and get the exact value you really need.

**Comment by nipun0212** [comment]
Hi Maxim,
 
Element.all is not working for child.
 
var e = element(by.id("page1-intHeader-BarLeft")) // can be any locator
.element.all(by.control({
controlType: "sap.m.Button"
})); // will look for buttons in the header

Please check the code in red.

Error :- It says e.element.all is not a function

But if I change it to e.element(by…..) it gets the first element and displays it.

**Comment by tsaleksandrova** [comment]
Hi,
please refer to protractor api documentation about element.all and iterations, as this is what we are currently using. we have a test for ancestor locator in e2e/browser/specs/by_control.spec.js that you can also check out

**Comment by nipun0212** [comment]
Thanks, Maxim. By referring to  e2e/browser/specs/by_control.spec.js I got the correct syntax.

**Comment by maximnaidenov** [comment]
Closing as the issue is resolved.
